name: bashomosko
favicon: null
layout_spectrum: 0.30648
typography_spectrum: 0.26489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92449a'
    - '#ffffff'
    - '#29c6d2'
    - '#c2b4cb'
    - '#c2ef10'
  brandStrength: 0.6875
  lightness: 0.006112866103649139
  saturation: 0.6037520067766309
  rhythmicContrast: 0.2250702646560967
purpose: []
