name: bashomosko
favicon: null
layout_spectrum: 0.17583477147854865
typography_spectrum: 0.14094415958970785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2661325503140688
  lightness: 0.006112866103649139
  saturation: 0.6037520067766309
  rhythmicContrast: 0.2250702646560967
purpose: []
